### ISSUE TITLE
Notify user of new version or allow for auto updates when launching application

### ISSUE THREAD

**Issue by Regardt** [donovanvanheerden/redsmith#22]

**Comment by donovanvanheerden** [comment]
Need to review [lens](https://github.com/lensapp/lens) code, since that is the desired effect for automatic updates. Try as best as possbile to not need to pay for code signing certificates...

**Comment by donovanvanheerden** [comment]
![image](https://user-images.githubusercontent.com/13114346/155460303-cb1e98e5-46e2-4c5b-8dda-3084396db252.png)

This is great and all as a first implementation...

Released from v0.2.1 🎉
