### ISSUE TITLE
Search for RedisKeys

### ISSUE THREAD

**Issue by donovanvanheerden** [donovanvanheerden/redsmith#3]
Ability to search / filter for redis keys

- [x] Include search keys component below keylist header
- [x] Add dropdown / search options for `Containing Value`, `Starts With`, `Ends With` or `Pattern Matching`
- [x] Extend Redis Client implementation on main process to support searching using the search options
- [ ] Implement MessageType for searching with request / response messages
- [x] Implement WebIpc function for sending request and receving response from the main process
- [ ] Wire up search component to use WebIPC for searching instead of directly filtering on keys list

**Comment by Magitekwarrior** [comment]
Will use the RedisAPI to search for keys instead of using app-level filter.
- Need to create flag to choose (Containing... vs Matching pattern) - check redily search function.
